from pygments.style import Style
from pygments.token import (
    _TokenType,
    Token,
    Text,
    Whitespace,
    Escape,
    Error,
    Other,
    Keyword,
    Name,
    Literal,
    String,
    Number,
    Operator,
    Punctuation,
    Comment,
    Generic,
)


white = "#FFFFFF"
light_grey = "#666666"
dark_grey = "#444444"
black = "#000000"


class MonochromeStyle(Style):
    default_style = ""

    styles = {
        Token: f"{black}",
        Text: f"{black}",
        # Whitespace: f'{black}',
        # Escape: f'{black}',
        # Error: f'{black}',
        # Other: f'{black}',
        Keyword: f"bold {dark_grey}",
        # Keyword.Constant: f'',
        # Keyword.Declaration: f'',
        # Keyword.Namespace: f'',
        # Keyword.Pseudo: f'',
        # Keyword.Reserved: f'',
        # Keyword.Type: f'',
        Name: f"{black}",
        # Name.Attribute: f'',
        # Name.Builtin: f'',
        # Name.Builtin.Pseudo: f'',
        # Name.Class: f'',
        # Name.Constant: f'',
        # Name.Decorator: f'',
        # Name.Entity: f'',
        # Name.Exception: f'',
        # Name.Function: f'',
        # Name.Function.Magic: f'',
        # Name.Property: f'',
        # Name.Label: f'',
        # Name.Namespace: f'',
        # Name.Other: f'',
        # Name.Tag: f'',
        # Name.Variable: f'',
        # Name.Variable.Class: f'',
        # Name.Variable.Global: f'',
        # Name.Variable.Instance: f'',
        # Name.Variable.Magic: f'',
        Literal: f"{dark_grey}",
        # Literal.Date: f'',
        String: f"{dark_grey}",
        # String.Affix: f'',
        # String.Backtick: f'',
        # String.Char: f'',
        # String.Delimiter: f'',
        # String.Doc: f'',
        # String.Double: f'',
        # String.Escape: f'',
        # String.Heredoc: f'',
        # String.Interpol: f'',
        # String.Other: f'',
        # String.Regex: f'',
        # String.Single: f'',
        # String.Symbol: f'',
        Number: f"{dark_grey}",
        # Number.Bin: f'',
        # Number.Float: f'',
        # Number.Hex: f'',
        # Number.Integer: f'',
        # Number.Integer.Long: f'',
        # Number.Oct: f'',
        Operator: f"{dark_grey}",
        # Operator.Word: f'',
        Punctuation: f"{dark_grey}",
        Comment: f"italic {light_grey}",
        # Comment.Hashbang: f'',
        # Comment.Multiline: f'',
        # Comment.Preproc: f'',
        # Comment.PreprocFile: f'',
        # Comment.Single: f'',
        # Comment.Special: f'',
        Generic: f"{black}",
        # Generic.Deleted: f'',
        # Generic.Emph: f'',
        # Generic.Error: f'',
        # Generic.Heading: f'',
        # Generic.Inserted: f'',
        # Generic.Output: f'',
        # Generic.Prompt: f'',
        # Generic.Strong: f'',
        # Generic.Subheading: f'',
        # Generic.Traceback: f'',
    }
